<a href="https://colab.research.google.com/github/Jack-Morgan22/BigData/blob/main/BigData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
#Data Analysis Libraries
import numpy as np
import pandas as pd

#Visualisation Libraries
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

#Ignore Warnings
import warnings
warnings.filterwarnings('ignore')

#Google Colab Import Files
from google.colab import files
import io

In [8]:
uploaded = files.upload()

Saving nomis_2024_03_04_132215.csv to nomis_2024_03_04_132215 (1).csv
Saving NS-SEC_2021.csv to NS-SEC_2021 (1).csv
Saving table-1-2020-21.csv to table-1-2020-21 (2).csv

In [9]:
GradData = pd.read_csv(io.BytesIO(uploaded['table-1-2020-21 (2).csv']))
AreaQuali = pd.read_csv(io.BytesIO(uploaded['nomis_2024_03_04_132215 (1).csv']))
SERank = pd.read_csv(io.BytesIO(uploaded['NS-SEC_2021 (1).csv']))

In [10]:
#Testing CSV Files Have Correctly Imported
print(GradData.columns)
print(AreaQuali.columns)
print(SERank.columns)

Index(['UKPRN', 'Provider name', 'Country of provider', 'Domicile',
       'Level of qualification obtained', 'Mode of former study',
       'Interim study', 'Sex', 'Activity', 'Academic year', 'Number'],
      dtype='object')
Index(['2022 local authorities: county', 'No qualifications',
       'Level 1 and entry level qualifications', 'Level 2 qualifications',
       'Apprenticeship', 'Level 3 qualifications',
       'Level 4 qualifications or above', 'Other qualifications'],
      dtype='object')
Index(['ONSConstID', 'ConstituencyName', 'RegNationID', 'RegNationName',
       'NatComparator', 'variables', 'groups', 'Con_num', 'Con_pc', 'RN_pc',
       'Nat_pc', 'ranking_total', 'rank'],
      dtype='object')

In [12]:
#See A Summary Of All The Datasets
GradData.describe(include = "all")

,UKPRN,Provider name,Country of provider,Domicile,Level of qualification obtained,Mode of former study,Interim study,Sex,Activity,Academic year,Number
count,1.048561e+06,1048561,1048561,1048561,1048561,1048561,1048561,1048561,1048561,1048561,1.048561e+06
unique,NaN,340,5,4,3,3,2,4,13,1,NaN
top,NaN,The Open University,All,All,All,All,Include significant interim study,All,Full-time employment,2020/21,NaN
freq,NaN,6656,522880,409663,405997,394115,524862,329004,80659,1048561,NaN
mean,1.000964e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.053909e+01
std,1.331511e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.189053e+02
min,1.000006e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00
25%,1.000386e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00
50%,1.000714e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00
75%,1.000782e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+01
max,1.008659e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.537500e+04

In [13]:
#See A Summary Of All The Datasets
AreaQuali.describe(include = "all")

,2022 local authorities: county,No qualifications,Level 1 and entry level qualifications,Level 2 qualifications,Apprenticeship,Level 3 qualifications,Level 4 qualifications or above,Other qualifications
count,174,174,174,174,174,174,174,174
unique,174,173,173,174,173,174,174,173
top,Darlington,"11,418","11,604","6,925","4,086","11,297","17,750","1,597"
freq,1,2,2,1,2,1,1,2

In [14]:
#See A Summary Of All The Datasets
SERank.describe(include = "all")

,ONSConstID,ConstituencyName,RegNationID,RegNationName,NatComparator,variables,groups,Con_num,Con_pc,RN_pc,Nat_pc,ranking_total,rank
count,5157,5157,5157,5157,5157,5157,5157,5157.000000,5157.000000,5157.000000,5157.000000,5157.000000,5157.00000
unique,573,573,10,10,1,9,5,NaN,NaN,NaN,NaN,NaN,NaN
top,E14000530,Aldershot,E12000008,South East,England & Wales,"Higher managerial, administrative and professi...",Routine and manual occupations,NaN,NaN,NaN,NaN,NaN,NaN
freq,9,9,756,756,5157,573,1719,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9417.561761,0.111111,0.111111,0.111111,0.236970,287.00000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4614.468678,0.050603,0.041117,0.038580,0.108914,165.42664
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1969.000000,0.022328,0.038670,0.053959,0.032813,1.00000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5768.000000,0.070558,0.079399,0.085120,0.174362,144.00000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8851.000000,0.106157,0.111662,0.113632,0.244566,287.00000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11489.000000,0.135741,0.122894,0.120659,0.313520,430.00000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34238.000000,0.345145,0.218946,0.199105,0.556306,573.00000